+++
draft = false
title = "face_recognition_models 0.3.0-4"
version = "0.3.0-4"
date = "2023-10-11T19:04:57"
categories = ['devel-extra']
upstreamurl = "http://pypi.python.org/pypi/face_recognition_models"
arch = "x86_64"
size = "91156720"
usize = "132051213"
sha1sum = "0b7714663902ed94f108d54c5940c3455054da05"
depends = "['python3>=3.10']"
files = "['usr/', 'usr/lib/', 'usr/lib/python3.12/', 'usr/lib/python3.12/site-packages/', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/PKG-INFO', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/SOURCES.txt', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/dependency_links.txt', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/not-zip-safe', 'usr/lib/python3.12/site-packages/face_recognition_models-0.3.0-py3.12.egg-info/top_level.txt', 'usr/lib/python3.12/site-packages/face_recognition_models/', 'usr/lib/python3.12/site-packages/face_recognition_models/__init__.py', 'usr/lib/python3.12/site-packages/face_recognition_models/__pycache__/', 'usr/lib/python3.12/site-packages/face_recognition_models/__pycache__/__init__.cpython-312.pyc', 'usr/lib/python3.12/site-packages/face_recognition_models/models/', 'usr/lib/python3.12/site-packages/face_recognition_models/models/dlib_face_recognition_resnet_model_v1.dat', 'usr/lib/python3.12/site-packages/face_recognition_models/models/mmod_human_face_detector.dat', 'usr/lib/python3.12/site-packages/face_recognition_models/models/shape_predictor_5_face_landmarks.dat', 'usr/lib/python3.12/site-packages/face_recognition_models/models/shape_predictor_68_face_landmarks.dat', 'usr/share/', 'usr/share/doc/', 'usr/share/doc/face_recognition_models-0.3.0/', 'usr/share/doc/face_recognition_models-0.3.0/LICENSE', 'usr/share/doc/face_recognition_models-0.3.0/README.rst']"
+++
Trained models for the face_recognition python library