+++
draft = false
title = "python3-exceptiongroup 1.1.3-1"
version = "1.1.3-1"
date = "2023-11-03T22:40:30"
categories = ['devel-extra']
upstreamurl = "http://pypi.python.org/pypi/exceptiongroup"
arch = "x86_64"
size = "28376"
usize = "138027"
sha1sum = "27d2defb40cc48a393c28cb4f0243232d53241d4"
depends = "['python3']"
files = "['usr/', 'usr/lib/', 'usr/lib/python3.12/', 'usr/lib/python3.12/site-packages/', 'usr/lib/python3.12/site-packages/exceptiongroup-1.1.3.dist-info/', 'usr/lib/python3.12/site-packages/exceptiongroup-1.1.3.dist-info/LICENSE', 'usr/lib/python3.12/site-packages/exceptiongroup-1.1.3.dist-info/METADATA', 'usr/lib/python3.12/site-packages/exceptiongroup-1.1.3.dist-info/RECORD', 'usr/lib/python3.12/site-packages/exceptiongroup-1.1.3.dist-info/WHEEL', 'usr/lib/python3.12/site-packages/exceptiongroup/', 'usr/lib/python3.12/site-packages/exceptiongroup/__init__.py', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/__init__.cpython-312.opt-1.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/__init__.cpython-312.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_catch.cpython-312.opt-1.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_catch.cpython-312.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-312.opt-1.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-312.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_formatting.cpython-312.opt-1.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_formatting.cpython-312.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_version.cpython-312.opt-1.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/__pycache__/_version.cpython-312.pyc', 'usr/lib/python3.12/site-packages/exceptiongroup/_catch.py', 'usr/lib/python3.12/site-packages/exceptiongroup/_exceptions.py', 'usr/lib/python3.12/site-packages/exceptiongroup/_formatting.py', 'usr/lib/python3.12/site-packages/exceptiongroup/_version.py', 'usr/lib/python3.12/site-packages/exceptiongroup/py.typed', 'usr/share/', 'usr/share/doc/', 'usr/share/doc/python3-exceptiongroup-1.1.3/', 'usr/share/doc/python3-exceptiongroup-1.1.3/LICENSE', 'usr/share/doc/python3-exceptiongroup-1.1.3/README.rst']"
+++
Backport of PEP 654 (exception groups)